# @package _global_

# specify here default training configuration
defaults:
  - model: vocals
  - paths: default.yaml
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

#hydra:
#  run:
#    dir: ${get_eval_log_dir:${ckpt_path}}

#ckpt_path: "G:\\Experiments\\KLRef\\vocals.onnx"
ckpt_path:
mixture_path:
batch_size: 4
#device: 'cuda:0'
device: 'cpu'

double_chunk: False

overlap_add:
  overlap_rate: 0.5
  tmp_root: ${paths.root_dir}/tmp # for saving temp chunks, since we use ffmpeg and will need io to disk
  samplerate: 44100